# DATASOURCE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum-api
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true